runs:
  using: composite
  steps:
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/uv
        key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'requirements.txt') }}
        restore-keys: |
          uv-${{ runner.os }}-

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        version: "latest"
        python-version: 3.12