# Generated by Django 6.1.1 on 2026-09-05 12:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("CHEQUE", "Cheque"),
                            ("ONLINE", "Online"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="payment_pay_status_124d3d_idx"
                    ),
                    models.Index(
                        fields=["method"], name="payment_pay_method_521bbf_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="payment_pay_created_c2327c_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="payment_pay_status_e53604_idx",
                    ),
                ],
            },
        ),
    ]
