# Generated by Django 5.1.7 on 2025-03-29 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country_short", models.CharField(max_length=10)),
                ("country_long", models.CharField(blank=True, max_length=100)),
                (
                    "country_long_en",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country_long_ko",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language_name", models.CharField(blank=True, max_length=255)),
                (
                    "language_name_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "language_name_ko",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("province_name", models.CharField(blank=True, max_length=255)),
                (
                    "province_name_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "province_name_ko",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city_name", models.CharField(blank=True, max_length=255)),
                (
                    "city_name_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "city_name_ko",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="options.province",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
            },
        ),
    ]
