# Generated by Django 6.1.1 on 2026-09-05 12:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country_short", models.CharField(max_length=10)),
                ("country_long", models.CharField(blank=True, max_length=100)),
                (
                    "country_long_en",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country_long_ko",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "indexes": [
                    models.Index(fields=["country_short"], name="idx_country_short"),
                    models.Index(fields=["country_long"], name="idx_country_long"),
                    models.Index(
                        fields=["country_long_en"], name="idx_country_long-en"
                    ),
                    models.Index(
                        fields=["country_long_ko"], name="idx_country_long-ko"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language_name", models.CharField(blank=True, max_length=255)),
                (
                    "language_name_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "language_name_ko",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["language_name"], name="idx_lang_name"),
                    models.Index(fields=["language_name_en"], name="idx_lang_name-en"),
                    models.Index(fields=["language_name_ko"], name="idx_lang_name-ko"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("province_name", models.CharField(blank=True, max_length=255)),
                (
                    "province_name_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "province_name_ko",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["province_name"], name="idx_province_name"),
                    models.Index(
                        fields=["province_name_en"], name="idx_province_name-en"
                    ),
                    models.Index(
                        fields=["province_name_ko"], name="idx_province_name-ko"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city_name", models.CharField(blank=True, max_length=255)),
                (
                    "city_name_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "city_name_ko",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="options.province",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "indexes": [
                    models.Index(fields=["province"], name="idx_city_province"),
                    models.Index(fields=["city_name"], name="idx_city_name"),
                    models.Index(
                        fields=["province", "city_name"], name="idx_city_prov_city"
                    ),
                    models.Index(fields=["city_name_en"], name="idx_city_name-en"),
                    models.Index(fields=["city_name_ko"], name="idx_city_name-ko"),
                    models.Index(
                        fields=["province", "city_name_en"],
                        name="idx_city_prov_city-en",
                    ),
                    models.Index(
                        fields=["province", "city_name_ko"],
                        name="idx_city_prov_city-ko",
                    ),
                ],
            },
        ),
    ]
