# Generated by Django 6.1.1 on 2026-09-05 12:41

import uuid

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag_name", models.CharField(blank=True, max_length=255)),
                (
                    "tag_name_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tag_name_ko",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["tag_name"],
                "indexes": [
                    models.Index(fields=["tag_name"], name="idx_forum_tag_name"),
                    models.Index(fields=["tag_name_en"], name="idx_forum_tag_name-en"),
                    models.Index(fields=["tag_name_ko"], name="idx_forum_tag_name-ko"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("total_like", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "total_comment",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forums",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Forum Author",
                    ),
                ),
                ("tags", models.ManyToManyField(related_name="forums", to="forum.tag")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "image",
                    core.models.CompressedImageField(
                        blank=True,
                        null=True,
                        quality=75,
                        upload_to=core.models.CompressedImageField.get_content_file_path,
                        width=1920,
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_comments",
                        to="forum.forum",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="forum.forumcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forum_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Comment by",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["forum", "-created_at"],
                        name="forum_forum_forum_i_75d39a_idx",
                    ),
                    models.Index(
                        fields=["forum", "parent_comment"],
                        name="forum_forum_forum_i_83dd98_idx",
                    ),
                    models.Index(
                        fields=["user"], name="forum_forum_user_id_b1ca1b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ForumImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    core.models.CompressedImageField(
                        quality=75,
                        upload_to=core.models.CompressedImageField.get_content_file_path,
                        width=1920,
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="forum.forum",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["forum"], name="forum_forum_forum_i_f72111_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ForumLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_likes",
                        to="forum.forum",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forum_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["forum", "user"], name="forum_forum_forum_i_d014be_idx"
                    ),
                    models.Index(
                        fields=["user"], name="forum_forum_user_id_92c6e5_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="forum",
            index=models.Index(
                fields=["-created_at"], name="forum_forum_created_ecb455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forum",
            index=models.Index(fields=["user"], name="forum_forum_user_id_07b545_idx"),
        ),
        migrations.AddIndex(
            model_name="forum",
            index=models.Index(
                fields=["-total_like"], name="forum_forum_total_l_1faf63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forum",
            index=models.Index(fields=["slug"], name="forum_forum_slug_92767c_idx"),
        ),
    ]
