# Generated by Django 6.1.1 on 2026-09-05 12:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.helpers.helper_functions


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("room_id", models.CharField(max_length=256, unique=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="chat_rooms_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(blank=True, max_length=1024)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages_session",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attachment",
                    models.FileField(
                        upload_to=utils.helpers.helper_functions.content_file_path
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_images_log",
                        to="chat.chatlog",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["room"], name="chat_chatim_room_id_bf2c75_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["room_id"], name="chat_chatse_room_id_5b902b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["-created_at"], name="chat_chatse_created_6b8c2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatlog",
            index=models.Index(
                fields=["room", "created_at"], name="chat_chatlo_room_id_fb6d7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatlog",
            index=models.Index(
                fields=["room", "is_read"], name="chat_chatlo_room_id_0992f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatlog",
            index=models.Index(fields=["user"], name="chat_chatlo_user_id_eeec65_idx"),
        ),
    ]
