# Generated by Django 6.1.1 on 2026-09-05 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("article", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Article Author",
            ),
        ),
        migrations.AddIndex(
            model_name="articlecategory",
            index=models.Index(fields=["name"], name="article_art_name_03fb52_idx"),
        ),
        migrations.AddIndex(
            model_name="articlecategory",
            index=models.Index(
                fields=["-created_at"], name="article_art_created_c147e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlecategory",
            index=models.Index(
                fields=["name_en"], name="article_art_name_03fb52_idx-en"
            ),
        ),
        migrations.AddIndex(
            model_name="articlecategory",
            index=models.Index(
                fields=["name_ko"], name="article_art_name_03fb52_idx-ko"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="article.articlecategory",
            ),
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_comments",
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="article.articlecomment",
            ),
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Comment by",
            ),
        ),
        migrations.AddField(
            model_name="articlelike",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_like",
                to="article.article",
            ),
        ),
        migrations.AddField(
            model_name="articlelike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Liked by",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-created_at"], name="article_art_created_d3bafd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category"], name="article_art_categor_74b327_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["user"], name="article_art_user_id_e5bffa_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "-created_at"],
                name="article_art_categor_8750e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-total_like"], name="article_art_total_l_399761_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="article_art_slug_403059_idx"),
        ),
        migrations.AddIndex(
            model_name="articlecomment",
            index=models.Index(
                fields=["article", "-created_at"], name="article_art_article_885968_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlecomment",
            index=models.Index(
                fields=["article", "parent_comment"],
                name="article_art_article_0eaee1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="articlecomment",
            index=models.Index(fields=["user"], name="article_art_user_id_e9151d_idx"),
        ),
        migrations.AddIndex(
            model_name="articlecomment",
            index=models.Index(
                fields=["parent_comment"], name="article_art_parent__4f15e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlelike",
            index=models.Index(
                fields=["article", "user"], name="article_art_article_f5a70a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlelike",
            index=models.Index(fields=["user"], name="article_art_user_id_0590cd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="articlelike",
            unique_together={("article", "user")},
        ),
    ]
