from .base_settings import *
from .cors_settings import *
from .database_settings import *
from .dj_rest_auth_settings import *
from .drf_settings import *
from .drf_spectacular_settings import *
from .email_settings import *
from .fcm_django_settings import *
from .language_settings import *
from .payment_settings import *
from .redis_settings import *
from .sms_settings import *
from .social_auth_settings import *
from .storage_settings import *
from .tinymce_settings import *
