from .base_settings import env

SOLAPI_API_KEY = env("SOLAPI_API_KEY", "")
SOLAPI_API_SECRET = env("SOLAPI_API_SECRET", "")
SOLAPI_PHONE_NUMBER = env("SOLAPI_PHONE_NUMBER", "")

BULKSMS_BD_NET_API_KEY = env("BULKSMS_BD_NET_API_KEY", "")
BULKSMS_BD_NET_SENDER_ID = env("BULKSMS_BD_NET_SENDER_ID", "")
BULKSMS_BD_NET_API_URL = env("BULKSMS_BD_NET_API_URL", "")
