# Generated by Django 5.1.7 on 2025-03-29 09:18

from django.db import migrations, models

import utils.helper.helper_functions


class Migration(migrations.Migration):
    dependencies = [
        ("authentications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=100,
                unique=True,
                validators=[utils.helper.helper_functions.validate_email],
                verbose_name="Email",
            ),
        ),
    ]
